# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_sheet', models.CharField(max_length=100)),
                ('to_sheet', models.CharField(max_length=100)),
                ('from_tab', models.CharField(max_length=100)),
                ('to_tab', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_row', models.CharField(max_length=10)),
                ('updated_col', models.CharField(max_length=10)),
                ('updated_range', models.CharField(max_length=100)),
            ],
        ),
    ]
