# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_io', '0002_auto_20160628_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(default=datetime.datetime(2016, 6, 29, 10, 42, 14, 8766, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
