# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets_io', '0003_log_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='updated_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_row',
            field=models.IntegerField(default=0),
        ),
    ]
